Enable checker from execution log to identify the result
Signed-off-by: hydai <hydai@secondstate.io>

diff --git a/.github/workflows/crio.yml b/.github/workflows/crio.yml
--- a/.github/workflows/crio.yml
+++ b/.github/workflows/crio.yml
@@ -93,9 +93,22 @@ jobs:
         env:
           TAG: ${{ matrix.tag }}
         run: |
-          bash crio/simple_wasi_application.sh --tag=$TAG
+          bash crio/simple_wasi_application.sh --tag=$TAG > dump.log 2>&1
 
       - name: Display crun and wasmedge version
         run: |
           crun --version
           wasmedge --version
+
+      - name: Dump the log of execution
+        run: |
+          cat dump.log
+
+      - name: Check the result
+        run: |
+          if grep -q "Printed from wasi: This is from a main function" dump.log; then
+            echo -e "Execution Success!"
+          else
+            echo -e "Execution Fail! Please check the above log for details"
+            exit 1
+          fi
