Enable more options for the various situations
Signed-off-by: hydai <hydai@secondstate.io>

diff --git a/.github/workflows/kubernetes-crio-server.yml b/.github/workflows/kubernetes-crio-server.yml
--- a/.github/workflows/kubernetes-crio-server.yml
+++ b/.github/workflows/kubernetes-crio-server.yml
@@ -1,4 +1,4 @@
-name: k8s-crio  http server
+name: k8s-crio http server
 
 concurrency:
   group: k8s-crio-server-${{ github.head_ref }}
@@ -21,6 +21,7 @@ on:
 jobs:
   k8s_crio_server:
     strategy:
+      fail-fast: false
       matrix:
         include:
           - name: "WasmEdge latest release, Crun master"
@@ -97,14 +98,30 @@ jobs:
         run: sleep 1200s
         shell: bash
 
+      - name: Dump the log of k8s setup
+        run: |
+          cat k8s.log
+
       - name: Run WasmEdge in k8s
         env:
           TAG: ${{ matrix.tag }}
         run: |
-          cat k8s.log
-          bash kubernetes_crio/http_server/http_server_application.sh --tag=$TAG
+          bash kubernetes_crio/http_server/http_server_application.sh --tag=$TAG > dump.log 2>&1
 
       - name: Display crun and wasmedge version
         run: |
           crun --version
           wasmedge --version
+
+      - name: Dump the log of execution
+        run: |
+          cat dump.log
+
+      - name: Check the result
+        run: |
+          if grep -q "echo: name=WasmEdge" dump.log; then
+            echo -e "Execution Success!"
+          else
+            echo -e "Execution Fail! Please check the above log for details"
+            exit 1
+          fi
diff --git a/.github/workflows/kubernetes-crio.yml b/.github/workflows/kubernetes-crio.yml
--- a/.github/workflows/kubernetes-crio.yml
+++ b/.github/workflows/kubernetes-crio.yml
@@ -29,36 +29,42 @@ jobs:
             crun: ""
             zh: "FALSE"
             tag: "latest"
+            variant: "compat-smart"
           - name: "WasmEdge 0.9.1, Crun 1.4.5"
             latest: false
             wasmedge: "0.9.1"
             crun: "1.4.5"
             zh: "FALSE"
             tag: "compat"
+            variant: "compat"
           - name: "WasmEdge 0.10.0, Crun 1.5"
             latest: false
             wasmedge: "0.10.0"
             crun: "1.5"
             zh: "FALSE"
-            tag: "latest"
+            tag: "compat-smart"
+            variant: "compat-smart"
           - name: "WasmEdge latest release, Crun master, ZH"
             latest: true
             wasmedge: ""
             crun: ""
             zh: "TRUE"
             tag: "latest"
+            variant: "compat-smart"
           - name: "WasmEdge 0.9.1, Crun 1.4.5, ZH"
             latest: false
             wasmedge: "0.9.1"
             crun: "1.4.5"
             zh: "TRUE"
             tag: "compat"
+            variant: "compat"
           - name: "WasmEdge 0.10.0, Crun 1.5, ZH"
             latest: false
             wasmedge: "0.10.0"
             crun: "1.5"
             zh: "TRUE"
-            tag: "latest"
+            tag: "compat-smart"
+            variant: "compat-smart"
     runs-on: ubuntu-20.04
     name: ${{ matrix.name }}
 
@@ -97,14 +103,31 @@ jobs:
         run: sleep 1200s
         shell: bash
 
+      - name: Dump the log of k8s setup
+        run: |
+          cat k8s.log
+
       - name: Run WasmEdge in k8s
         env:
           TAG: ${{ matrix.tag }}
+          VARIANT: ${{ matrix.variant }}
         run: |
-          cat k8s.log
-          bash kubernetes_crio/simple_wasi_application.sh --tag=$TAG
+          bash kubernetes_crio/simple_wasi_application.sh --tag=$TAG --variant=$VARIANT > dump.log 2>&1
 
       - name: Display crun and wasmedge version
         run: |
           crun --version
           wasmedge --version
+
+      - name: Dump the log of execution
+        run: |
+          cat dump.log
+
+      - name: Check the result
+        run: |
+          if grep -q "Printed from wasi: This is from a main function" dump.log; then
+            echo -e "Execution Success!"
+          else
+            echo -e "Execution Fail! Please check the above log for details"
+            exit 1
+          fi
